apiVersion: v1
kind: Service
metadata:
  name: kdemo-service
  labels:
    app: kdemo
spec:
  selector:
    app: kdemo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
